server:
  port: 10080
master:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/store?characterEncoding=UTF-8
    username: root
    password: 123456
slave:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/store?characterEncoding=UTF-8
    username: root
    password: 123456